#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${1:-neuroroute-c}"
MARKER_FILE=".generated_by_neuro_router_builder"

if [[ -e "$PROJECT_DIR" ]]; then
    if [[ -f "$PROJECT_DIR/$MARKER_FILE" ]]; then
        rm -rf "$PROJECT_DIR"
    else
        backup="${PROJECT_DIR}_backup_$(date +%Y%m%d_%H%M%S)"
        mv "$PROJECT_DIR" "$backup"
        printf 'Existing directory moved to: %s\n' "$backup"
    fi
fi

mkdir -p \
    "$PROJECT_DIR/include/asm" \
    "$PROJECT_DIR/include/mm" \
    "$PROJECT_DIR/src" \
    "$PROJECT_DIR/tests" \
    "$PROJECT_DIR/examples" \
    "$PROJECT_DIR/build" \
    "$PROJECT_DIR/bin" \
    "$PROJECT_DIR/lib"

cat > "$PROJECT_DIR/$MARKER_FILE" <<'EOF'
This repository was generated by build_neuroroute_c.sh.
EOF

cat > "$PROJECT_DIR/.gitignore" <<'EOF'
build/
bin/
lib/
*.o
*.a
*.so
*.dylib
*.dll
*.exe
*.log
*.plist
.DS_Store
EOF

cat > "$PROJECT_DIR/include/asm/primitives.h" <<'EOF'
#ifndef NEURO_ASM_PRIMITIVES_H
#define NEURO_ASM_PRIMITIVES_H

#include <stdatomic.h>

/*
 * Portable C11 spin lock used for topology changes.
 * The routing counter itself still uses the original GCC/Clang atomic builtin.
 */
typedef struct {
    atomic_flag flag;
} spinlock_t;

#define SPINLOCK_INITIALIZER { ATOMIC_FLAG_INIT }

static inline void spinlock_init(spinlock_t *lock) {
    if (lock != NULL) {
        atomic_flag_clear_explicit(&lock->flag, memory_order_release);
    }
}

static inline void spinlock_lock(spinlock_t *lock) {
    while (atomic_flag_test_and_set_explicit(&lock->flag, memory_order_acquire)) {
        /* Busy wait: appropriate only for very short critical sections. */
    }
}

static inline void spinlock_unlock(spinlock_t *lock) {
    atomic_flag_clear_explicit(&lock->flag, memory_order_release);
}

#endif
EOF

cat > "$PROJECT_DIR/include/neuro.h" <<'EOF'
#ifndef NEURO_H
#define NEURO_H

#include <stddef.h>
#include <stdint.h>

#include <asm/primitives.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_SYSTEM_NODES 1024u
#define NEURO_ACTIVATION_THRESHOLD 100u

#define ALPHA_NORMALIZER 0.030882
#define BETA_EXPONENT 1.420317

/*
 * Synaptic Connection Entry representing an active call dependency (1 Road).
 * Alignment is retained to reduce the chance of cache-line sharing.
 */
struct __attribute__((aligned(64))) synapse_edge {
    uint64_t target_function_address;
    uint32_t current_synaptic_weight;
    uint32_t total_spike_count;
    struct synapse_edge *next_road;
};

/* High-Speed Topological Node Entry (The Functional Unit/Neuron). */
struct neural_node {
    uint64_t function_base_address;
    uint32_t out_degree_count;
    struct synapse_edge *connection_list;
    spinlock_t state_lock;
};

/* Reset all nodes and release all dynamically added roads. */
void neuro_router_reset(void);

/* Configure a node's local fallback identifier/address. */
int neuro_set_node(uint64_t node_id, uint64_t function_base_address);

/* Add one outbound road. Roads are traversed in insertion order. */
int neuro_add_edge(
    uint64_t source_node_id,
    uint64_t target_function_address,
    uint32_t synaptic_weight
);

/*
 * Select the highest-weight outbound road. If no road exists, return the
 * node's local fallback. Inputs below the threshold return zero.
 */
uint64_t route_synaptic_signal(
    uint64_t source_node_id,
    uint32_t input_excitation
);

/* Read-only node state without copying the internal lock or edge pointer. */
struct neural_node_snapshot {
    uint64_t function_base_address;
    uint32_t out_degree_count;
};

int neuro_get_node_snapshot(
    uint64_t node_id,
    struct neural_node_snapshot *out_snapshot
);
int neuro_get_edge_spike_count(
    uint64_t source_node_id,
    uint64_t target_function_address,
    uint32_t *out_spike_count
);

#ifdef __cplusplus
}
#endif

#endif
EOF

cat > "$PROJECT_DIR/include/mm/spatial_pool.h" <<'EOF'
#ifndef NEURO_MM_SPATIAL_POOL_H
#define NEURO_MM_SPATIAL_POOL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_SPATIAL_CHUNKS 256u
#define SPATIAL_COORDINATE_WORDS 4u

/* Sparse Bit-Array chunk mapping active memory regions. */
struct sparse_memory_chunk {
    uint64_t memory_coordinates[SPATIAL_COORDINATE_WORDS];
    uint64_t physical_page_pointer;
    uint32_t spatial_density_score;
};

/* Clear all configured chunks. */
void spatial_pool_reset(void);

/* Configure one searchable chunk. */
int spatial_pool_set_chunk(
    size_t index,
    const uint64_t coordinates[SPATIAL_COORDINATE_WORDS],
    uint64_t physical_page_pointer,
    uint32_t initial_density_score
);

/*
 * Return the page belonging to the configured chunk with the minimum Hamming
 * distance from the supplied feature vector. The first best match wins.
 */
uint64_t allocate_spatial_memory(
    const uint64_t *feature_vector,
    size_t vector_size
);

/* Inspect a configured chunk without exposing the private pool directly. */
int spatial_pool_get_chunk(size_t index, struct sparse_memory_chunk *out_chunk);

#ifdef __cplusplus
}
#endif

#endif
EOF

cat > "$PROJECT_DIR/src/routing.c" <<'EOF'
#include <neuro.h>

#include <stdlib.h>
#include <string.h>

/* Global Routing Table holding the system topology. */
static struct neural_node global_routing_table[MAX_SYSTEM_NODES];
static atomic_bool router_initialized = ATOMIC_VAR_INIT(0);
static atomic_flag router_init_guard = ATOMIC_FLAG_INIT;

static void ensure_router_initialized(void) {
    if (atomic_load_explicit(&router_initialized, memory_order_acquire)) {
        return;
    }

    while (atomic_flag_test_and_set_explicit(
        &router_init_guard,
        memory_order_acquire
    )) {
        /* Wait only during first-use initialization. */
    }

    if (!atomic_load_explicit(&router_initialized, memory_order_relaxed)) {
        memset(global_routing_table, 0, sizeof(global_routing_table));
        for (size_t i = 0; i < MAX_SYSTEM_NODES; ++i) {
            spinlock_init(&global_routing_table[i].state_lock);
        }
        atomic_store_explicit(
            &router_initialized,
            1,
            memory_order_release
        );
    }

    atomic_flag_clear_explicit(&router_init_guard, memory_order_release);
}

static void free_edge_chain(struct synapse_edge *edge) {
    while (edge != NULL) {
        struct synapse_edge *next = edge->next_road;
        free(edge);
        edge = next;
    }
}

void neuro_router_reset(void) {
    ensure_router_initialized();

    for (size_t i = 0; i < MAX_SYSTEM_NODES; ++i) {
        struct neural_node *node = &global_routing_table[i];
        spinlock_lock(&node->state_lock);
        free_edge_chain(node->connection_list);
        node->connection_list = NULL;
        node->function_base_address = 0;
        node->out_degree_count = 0;
        spinlock_unlock(&node->state_lock);
    }
}

int neuro_set_node(uint64_t node_id, uint64_t function_base_address) {
    ensure_router_initialized();
    if (node_id >= MAX_SYSTEM_NODES) {
        return -1;
    }

    struct neural_node *node = &global_routing_table[node_id];
    spinlock_lock(&node->state_lock);
    node->function_base_address = function_base_address;
    spinlock_unlock(&node->state_lock);
    return 0;
}

int neuro_add_edge(
    uint64_t source_node_id,
    uint64_t target_function_address,
    uint32_t synaptic_weight
) {
    ensure_router_initialized();
    if (source_node_id >= MAX_SYSTEM_NODES) {
        return -1;
    }

    _Static_assert(
        sizeof(struct synapse_edge) % 64u == 0u,
        "synapse_edge size must be a multiple of its 64-byte alignment"
    );

    struct synapse_edge *new_edge = aligned_alloc(64u, sizeof(*new_edge));
    if (new_edge == NULL) {
        return -2;
    }
    memset(new_edge, 0, sizeof(*new_edge));

    new_edge->target_function_address = target_function_address;
    new_edge->current_synaptic_weight = synaptic_weight;
    new_edge->total_spike_count = 0;
    new_edge->next_road = NULL;

    struct neural_node *node = &global_routing_table[source_node_id];
    spinlock_lock(&node->state_lock);

    if (node->connection_list == NULL) {
        node->connection_list = new_edge;
    } else {
        struct synapse_edge *tail = node->connection_list;
        while (tail->next_road != NULL) {
            tail = tail->next_road;
        }
        tail->next_road = new_edge;
    }

    node->out_degree_count += 1;
    spinlock_unlock(&node->state_lock);
    return 0;
}

uint64_t route_synaptic_signal(uint64_t source_node_id, uint32_t input_excitation) {
    ensure_router_initialized();
    if (source_node_id >= MAX_SYSTEM_NODES) {
        return 0;
    }

    struct neural_node *node = &global_routing_table[source_node_id];

    /* Preserve the original activation short-circuit. */
    if (input_excitation < NEURO_ACTIVATION_THRESHOLD) {
        return 0;
    }

    spinlock_lock(&node->state_lock);

    struct synapse_edge *edge = node->connection_list;
    struct synapse_edge *selected_edge = NULL;
    uint32_t max_weight = 0;

    /* Preserve the original maximum-weight traversal and first-match tie rule. */
    while (edge != NULL) {
        if (edge->current_synaptic_weight > max_weight) {
            max_weight = edge->current_synaptic_weight;
            selected_edge = edge;
        }
        edge = edge->next_road;
    }

    uint64_t result = node->function_base_address;
    if (selected_edge != NULL) {
        __sync_fetch_and_add(&selected_edge->total_spike_count, 1);
        result = selected_edge->target_function_address;
    }

    spinlock_unlock(&node->state_lock);
    return result;
}

int neuro_get_node_snapshot(
    uint64_t node_id,
    struct neural_node_snapshot *out_snapshot
) {
    ensure_router_initialized();
    if (node_id >= MAX_SYSTEM_NODES || out_snapshot == NULL) {
        return -1;
    }

    struct neural_node *node = &global_routing_table[node_id];
    spinlock_lock(&node->state_lock);
    out_snapshot->function_base_address = node->function_base_address;
    out_snapshot->out_degree_count = node->out_degree_count;
    spinlock_unlock(&node->state_lock);
    return 0;
}

int neuro_get_edge_spike_count(
    uint64_t source_node_id,
    uint64_t target_function_address,
    uint32_t *out_spike_count
) {
    ensure_router_initialized();
    if (source_node_id >= MAX_SYSTEM_NODES || out_spike_count == NULL) {
        return -1;
    }

    struct neural_node *node = &global_routing_table[source_node_id];
    spinlock_lock(&node->state_lock);

    struct synapse_edge *edge = node->connection_list;
    while (edge != NULL) {
        if (edge->target_function_address == target_function_address) {
            *out_spike_count = edge->total_spike_count;
            spinlock_unlock(&node->state_lock);
            return 0;
        }
        edge = edge->next_road;
    }

    spinlock_unlock(&node->state_lock);
    return -2;
}
EOF

cat > "$PROJECT_DIR/src/spatial_pool.c" <<'EOF'
#include <mm/spatial_pool.h>

#include <limits.h>
#include <string.h>

static struct sparse_memory_chunk memory_pool[MAX_SPATIAL_CHUNKS];
static unsigned char chunk_configured[MAX_SPATIAL_CHUNKS];

void spatial_pool_reset(void) {
    memset(memory_pool, 0, sizeof(memory_pool));
    memset(chunk_configured, 0, sizeof(chunk_configured));
}

int spatial_pool_set_chunk(
    size_t index,
    const uint64_t coordinates[SPATIAL_COORDINATE_WORDS],
    uint64_t physical_page_pointer,
    uint32_t initial_density_score
) {
    if (index >= MAX_SPATIAL_CHUNKS || coordinates == NULL) {
        return -1;
    }

    memcpy(
        memory_pool[index].memory_coordinates,
        coordinates,
        sizeof(memory_pool[index].memory_coordinates)
    );
    memory_pool[index].physical_page_pointer = physical_page_pointer;
    memory_pool[index].spatial_density_score = initial_density_score;
    chunk_configured[index] = 1;
    return 0;
}

uint64_t allocate_spatial_memory(
    const uint64_t *feature_vector,
    size_t vector_size
) {
    if (feature_vector == NULL || vector_size == 0) {
        return 0;
    }

    const size_t compared_words =
        vector_size < SPATIAL_COORDINATE_WORDS
            ? vector_size
            : SPATIAL_COORDINATE_WORDS;

    uint64_t best_fit_page = 0;
    size_t best_fit_index = MAX_SPATIAL_CHUNKS;
    uint32_t minimum_hamming_distance = UINT_MAX;

    /* Preserve the original minimum-Hamming-distance search. */
    for (size_t i = 0; i < MAX_SPATIAL_CHUNKS; ++i) {
        if (!chunk_configured[i]) {
            continue;
        }

        uint32_t current_distance = 0;
        for (size_t j = 0; j < compared_words; ++j) {
            current_distance += (uint32_t)__builtin_popcountll(
                memory_pool[i].memory_coordinates[j] ^ feature_vector[j]
            );
        }

        if (current_distance < minimum_hamming_distance) {
            minimum_hamming_distance = current_distance;
            best_fit_page = memory_pool[i].physical_page_pointer;
            best_fit_index = i;
        }
    }

    /* Increment the selected chunk itself, not page modulo pool size. */
    if (best_fit_index < MAX_SPATIAL_CHUNKS) {
        __sync_fetch_and_add(
            &memory_pool[best_fit_index].spatial_density_score,
            1
        );
    }

    return best_fit_page;
}

int spatial_pool_get_chunk(size_t index, struct sparse_memory_chunk *out_chunk) {
    if (
        index >= MAX_SPATIAL_CHUNKS ||
        out_chunk == NULL ||
        !chunk_configured[index]
    ) {
        return -1;
    }

    *out_chunk = memory_pool[index];
    return 0;
}
EOF

cat > "$PROJECT_DIR/tests/test_routing.c" <<'EOF'
#include <neuro.h>

#include <assert.h>
#include <stdint.h>
#include <stdio.h>

static void test_activation_and_fallback(void) {
    neuro_router_reset();
    assert(neuro_set_node(7, 7007) == 0);
    assert(route_synaptic_signal(7, NEURO_ACTIVATION_THRESHOLD - 1) == 0);
    assert(route_synaptic_signal(7, NEURO_ACTIVATION_THRESHOLD) == 7007);
}

static void test_maximum_weight_selection_and_counter(void) {
    neuro_router_reset();
    assert(neuro_set_node(3, 3003) == 0);
    assert(neuro_add_edge(3, 111, 10) == 0);
    assert(neuro_add_edge(3, 222, 90) == 0);
    assert(neuro_add_edge(3, 333, 40) == 0);

    assert(route_synaptic_signal(3, 500) == 222);
    assert(route_synaptic_signal(3, 500) == 222);

    uint32_t spikes = 0;
    assert(neuro_get_edge_spike_count(3, 222, &spikes) == 0);
    assert(spikes == 2);

    struct neural_node_snapshot node = {0};
    assert(neuro_get_node_snapshot(3, &node) == 0);
    assert(node.function_base_address == 3003);
    assert(node.out_degree_count == 3);
}

static void test_first_match_wins_equal_weight(void) {
    neuro_router_reset();
    assert(neuro_add_edge(1, 1001, 50) == 0);
    assert(neuro_add_edge(1, 1002, 50) == 0);
    assert(route_synaptic_signal(1, 500) == 1001);
}

static void test_invalid_node(void) {
    assert(neuro_set_node(MAX_SYSTEM_NODES, 1) == -1);
    assert(neuro_add_edge(MAX_SYSTEM_NODES, 1, 1) == -1);
    assert(route_synaptic_signal(MAX_SYSTEM_NODES, 500) == 0);
}

int main(void) {
    test_activation_and_fallback();
    test_maximum_weight_selection_and_counter();
    test_first_match_wins_equal_weight();
    test_invalid_node();
    neuro_router_reset();
    puts("routing tests: PASS");
    return 0;
}
EOF

cat > "$PROJECT_DIR/tests/test_spatial_pool.c" <<'EOF'
#include <mm/spatial_pool.h>

#include <assert.h>
#include <stdint.h>
#include <stdio.h>

static void test_empty_and_invalid_inputs(void) {
    spatial_pool_reset();
    const uint64_t feature[4] = {1, 2, 3, 4};
    assert(allocate_spatial_memory(feature, 4) == 0);
    assert(allocate_spatial_memory(NULL, 4) == 0);
    assert(allocate_spatial_memory(feature, 0) == 0);
}

static void test_minimum_hamming_distance_and_density(void) {
    spatial_pool_reset();

    const uint64_t coordinates_a[4] = {0x00, 0x00, 0x00, 0x00};
    const uint64_t coordinates_b[4] = {0xFF, 0x0F, 0x00, 0x00};
    const uint64_t coordinates_c[4] = {0xF0, 0x0F, 0x00, 0x00};
    const uint64_t feature[4] = {0xF0, 0x0F, 0x00, 0x00};

    assert(spatial_pool_set_chunk(2, coordinates_a, 2002, 0) == 0);
    assert(spatial_pool_set_chunk(3, coordinates_b, 3003, 5) == 0);
    assert(spatial_pool_set_chunk(4, coordinates_c, 4004, 10) == 0);

    assert(allocate_spatial_memory(feature, 4) == 4004);

    struct sparse_memory_chunk selected = {0};
    struct sparse_memory_chunk other = {0};
    assert(spatial_pool_get_chunk(4, &selected) == 0);
    assert(spatial_pool_get_chunk(3, &other) == 0);
    assert(selected.spatial_density_score == 11);
    assert(other.spatial_density_score == 5);
}

static void test_first_match_wins_tie(void) {
    spatial_pool_reset();
    const uint64_t coordinates[4] = {7, 7, 7, 7};
    const uint64_t feature[4] = {7, 7, 7, 7};

    assert(spatial_pool_set_chunk(10, coordinates, 1010, 0) == 0);
    assert(spatial_pool_set_chunk(11, coordinates, 1111, 0) == 0);
    assert(allocate_spatial_memory(feature, 4) == 1010);
}

int main(void) {
    test_empty_and_invalid_inputs();
    test_minimum_hamming_distance_and_density();
    test_first_match_wins_tie();
    puts("spatial pool tests: PASS");
    return 0;
}
EOF

cat > "$PROJECT_DIR/examples/demo.c" <<'EOF'
#include <mm/spatial_pool.h>
#include <neuro.h>

#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

int main(void) {
    neuro_router_reset();
    spatial_pool_reset();

    neuro_set_node(0, 9000);
    neuro_add_edge(0, 1001, 25);
    neuro_add_edge(0, 1002, 90);
    neuro_add_edge(0, 1003, 40);

    uint64_t routed_target = route_synaptic_signal(0, 500);

    const uint64_t chunk_a[4] = {0x00, 0x00, 0x00, 0x00};
    const uint64_t chunk_b[4] = {0xAA, 0x55, 0x00, 0x00};
    const uint64_t feature[4] = {0xAA, 0x55, 0x00, 0x00};

    spatial_pool_set_chunk(0, chunk_a, 4096, 0);
    spatial_pool_set_chunk(1, chunk_b, 8192, 0);

    uint64_t selected_page = allocate_spatial_memory(feature, 4);

    printf("Selected route target: %" PRIu64 "\n", routed_target);
    printf("Selected spatial page: %" PRIu64 "\n", selected_page);

    neuro_router_reset();
    return 0;
}
EOF

cat > "$PROJECT_DIR/Makefile" <<'EOF'
CC ?= cc
AR ?= ar

CPPFLAGS := -Iinclude
BASE_CFLAGS := -std=c11 -Wall -Wextra -Wpedantic -Werror
CFLAGS ?= -O2

LIB_SOURCES := src/routing.c src/spatial_pool.c
LIB_OBJECTS := build/routing.o build/spatial_pool.o
LIBRARY := lib/libneuro_router.a

TEST_ROUTING := bin/test_routing
TEST_SPATIAL := bin/test_spatial_pool
DEMO := bin/neuro_demo

.PHONY: all test demo debug sanitize clean

all: $(LIBRARY) $(TEST_ROUTING) $(TEST_SPATIAL) $(DEMO)

build/routing.o: src/routing.c include/neuro.h include/asm/primitives.h
	@mkdir -p build
	$(CC) $(CPPFLAGS) $(BASE_CFLAGS) $(CFLAGS) -c $< -o $@

build/spatial_pool.o: src/spatial_pool.c include/mm/spatial_pool.h
	@mkdir -p build
	$(CC) $(CPPFLAGS) $(BASE_CFLAGS) $(CFLAGS) -c $< -o $@

$(LIBRARY): $(LIB_OBJECTS)
	@mkdir -p lib
	$(AR) rcs $@ $^

$(TEST_ROUTING): tests/test_routing.c $(LIBRARY)
	@mkdir -p bin
	$(CC) $(CPPFLAGS) $(BASE_CFLAGS) $(CFLAGS) $< $(LIBRARY) -o $@

$(TEST_SPATIAL): tests/test_spatial_pool.c $(LIBRARY)
	@mkdir -p bin
	$(CC) $(CPPFLAGS) $(BASE_CFLAGS) $(CFLAGS) $< $(LIBRARY) -o $@

$(DEMO): examples/demo.c $(LIBRARY)
	@mkdir -p bin
	$(CC) $(CPPFLAGS) $(BASE_CFLAGS) $(CFLAGS) $< $(LIBRARY) -o $@

test: $(TEST_ROUTING) $(TEST_SPATIAL)
	./$(TEST_ROUTING)
	./$(TEST_SPATIAL)

demo: $(DEMO)
	./$(DEMO)

debug: CFLAGS := -O0 -g3
debug: clean all test demo

sanitize: CFLAGS := -O1 -g3 -fno-omit-frame-pointer -fsanitize=address,undefined
sanitize: clean all
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 UBSAN_OPTIONS=halt_on_error=1 ./$(TEST_ROUTING)
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 UBSAN_OPTIONS=halt_on_error=1 ./$(TEST_SPATIAL)
	ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 UBSAN_OPTIONS=halt_on_error=1 ./$(DEMO)

clean:
	rm -rf build bin lib
EOF

cat > "$PROJECT_DIR/README.md" <<'EOF'
# NeuroRoute C

**A deterministic C11 routing and associative matching core for AI systems research.**

NeuroRoute C explores a simple question: how can neural-inspired execution graphs be implemented as transparent, reproducible systems code rather than probabilistic model behavior?

The project combines two compact mechanisms:

1. **Weighted graph routing** that selects the strongest outbound path from a node, records route usage atomically, and preserves a deterministic fallback.
2. **256-bit spatial matching** that compares binary feature vectors and returns the configured entry with the smallest Hamming distance.

The result is a small, dependency-free research prototype that can be inspected, tested, embedded, and extended without a model server or external service.

## Why it is interesting

Modern AI systems often need more than model inference. They also need predictable routing, memory lookup, fallback behavior, execution counters, and components that can be verified independently.

NeuroRoute C provides a low-level experimental base for studying those ideas in ordinary C:

- deterministic decisions instead of sampled outputs;
- inspectable graph topology instead of hidden model state;
- binary fingerprint matching instead of text-only retrieval;
- explicit fallback behavior;
- reproducible tests and sanitizer validation;
- no third-party runtime dependencies.

It is not a neural network and it does not train or generate content. The design is **neural-inspired**, while the execution remains conventional, deterministic systems programming.

## Core mechanisms

### 1. Maximum-weight graph routing

Each node contains a local fallback identifier and zero or more outbound roads. A road contains a target identifier, a weight, a usage counter, and a link to the next road.

When `route_synaptic_signal()` runs:

1. Excitation below `NEURO_ACTIVATION_THRESHOLD` returns `0`.
2. The selected node's roads are scanned in insertion order.
3. The road with the greatest weight is selected.
4. The first road wins if multiple roads share the same maximum weight.
5. The selected road's usage counter is incremented atomically.
6. A node with no roads returns its configured fallback identifier.

This creates predictable route selection while retaining counters that can support later analysis or controlled adaptation.

### 2. Hamming-distance spatial matching

Each spatial entry stores four 64-bit coordinate words, forming a 256-bit binary feature vector.

`allocate_spatial_memory()` compares an input vector with every configured entry and returns the page identifier associated with the smallest Hamming distance. Equal-distance matches are resolved deterministically by selecting the first configured entry.

The historical function name is retained, but the function does not allocate operating-system memory. It performs nearest-match lookup over a fixed in-memory table.

## Potential uses

NeuroRoute C can serve as a starting point for experiments involving:

- deterministic agent or tool routing;
- policy-controlled handler selection;
- fallback routing in AI pipelines;
- binary request fingerprint matching;
- associative lookup prototypes;
- execution-graph and topology research;
- route-frequency instrumentation;
- embedded or edge-system dispatch;
- reproducible comparisons between deterministic and model-driven decisions;
- teaching low-level graph structures, atomics, Hamming distance, and C testing.

These are possible directions, not built-in claims. Integration logic is still required for a specific application.

## Repository structure

```text
.
|-- include/
|   |-- asm/
|   |   `-- primitives.h
|   |-- mm/
|   |   `-- spatial_pool.h
|   `-- neuro.h
|-- src/
|   |-- routing.c
|   `-- spatial_pool.c
|-- tests/
|   |-- test_routing.c
|   `-- test_spatial_pool.c
|-- examples/
|   `-- demo.c
|-- Makefile
|-- LICENSE
`-- README.md
```

## Requirements

- GCC or Clang with C11 support
- `make`
- A Unix-like shell only when using the optional builder script

No Python environment, external API, model provider, database, network connection, or third-party C library is required.

## Build

```bash
make
```

This creates:

```text
lib/libneuro_router.a
bin/test_routing
bin/test_spatial_pool
bin/neuro_demo
```

## Run the tests

```bash
make test
```

Expected output:

```text
routing tests: PASS
spatial pool tests: PASS
```

## Run the CLI demonstration

```bash
make demo
```

Expected output:

```text
Selected route target: 1002
Selected spatial page: 8192
```

## Run sanitizer validation

```bash
make sanitize
```

This rebuilds and runs the tests and demonstration with AddressSanitizer and UndefinedBehaviorSanitizer.

## Integrate the library

Include the library headers from another C project:

```c
#include <neuro.h>
#include <mm/spatial_pool.h>
```

Then link against:

```text
lib/libneuro_router.a
```

The header files expose functions for reset and initialization, node configuration, edge insertion, deterministic route selection, spatial-entry configuration, nearest-match lookup, and state inspection.

## Design guarantees

The current implementation preserves these deterministic rules:

- the greatest route weight wins;
- the first route wins a weight tie;
- the first spatial entry wins a distance tie;
- low excitation returns zero;
- an empty node returns its fallback identifier;
- selected-route counters are incremented atomically;
- node and spatial-entry indices are bounds-checked;
- the spatial density counter is applied to the entry that was actually selected.

The constants `ALPHA_NORMALIZER` and `BETA_EXPONENT` are retained from the original prototype, but the present routing function does not apply a scaling equation.

## Project scope

NeuroRoute C is a compact research and systems-programming prototype. It does not train a model, discover application functions automatically, execute stored numeric identifiers as machine code, replace a vector database, or modify itself recursively.

Its purpose is to make deterministic routing and binary spatial matching concrete, inspectable, and easy to experiment with.

## License

MIT License. See `LICENSE`.
EOF

cat > "$PROJECT_DIR/LICENSE" <<'EOF'
MIT License

Copyright (c) 2026 Project contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF

printf '\nCreated %s\n' "$PROJECT_DIR"
printf 'Running release build and tests...\n'
make -C "$PROJECT_DIR" clean all test demo

if command -v clang >/dev/null 2>&1; then
    printf '\nRunning an additional Clang build and test...\n'
    make -C "$PROJECT_DIR" clean all test CC=clang
fi

printf '\nRunning sanitizer validation...\n'
make -C "$PROJECT_DIR" sanitize

printf '\nRemoving generated binaries so the repository remains source-only...\n'
make -C "$PROJECT_DIR" clean

printf '\nValidation complete.\n'
printf 'Project: %s\n' "$PROJECT_DIR"
printf 'Run tests later with: make -C %q test\n' "$PROJECT_DIR"
printf 'Run demo later with:  make -C %q demo\n' "$PROJECT_DIR"
